### ISSUE TITLE
Wrong field name in SubmitFeed

### ISSUE THREAD

**Issue by Kulimeya** [webjeyros/bing-webmaster-api#3]
The SubmitFeed action contains an error, which makes the request invalid.

If I send a SubmitFeed request I get:

`400 Error response:
{"ErrorCode":8,"Message":"ERROR!!! InvalidParameter"}`

According to the [Bing API doc](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bing.webmaster.api.interfaces.iwebmasterapi.submitfeed?view=bing-webmaster-dotnet) the fields have to be called "siteUrl" and "feedUrl" but the SubmitFeed class contains "url" and "feedUrl".

When I change the field name it works, otherwise I get the error above. Is it possible to fix it?

Thanks!

**Comment by webjeyros** [comment]
Fixed
